name: TeamTp
version: ${project.version}
main: com.github.ms5984.survivelist.teamtp.TeamTp
api-version: 1.17
authors: [ ItzShmulik, ms5984 ]
description: Teleport players to a starting area
commands:
  teamtp:
    permission: teamtp.use
  setteamtp:
    description: Set teamtp locations
    permission: teamtp.set
  delteamtp:
    description: Unset teamtp locations
    permission: teamtp.set
  teamtpreload:
    description: Reload TeamTp from files
    permission: teamtp.reload